name: Renovate
on:
    # Run on a schedule (e.g., every 4 hours)
    schedule:
        - cron: "0 */6 * * *"
    # Allow manual triggering for testing
    workflow_dispatch:

    push:
        branches:
            - main

        paths:
            - ".github/renovate.json5"
            - ".github/workflows/renovate.yml"

jobs:
    renovate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v5

            - name: Self-hosted Renovate
              uses: renovatebot/github-action@70b5ec2218c6ce8f475b2e6ee06afc8082751f02 # v40.1.11
              with:
                  configurationFile: .github/renovate.json5
                  token: ${{ secrets.RENOVATE_TOKEN }}
              env:
                  # Tell Renovate to run only on this specific repository
                  RENOVATE_REPOSITORIES: ${{ github.repository }}
                  # Optional: helpful for debugging initially
                  LOG_LEVEL: debug
